### ISSUE TITLE
Error during scrape

### ISSUE THREAD

**Issue by redfalcoon** [motebaya/Picuki#1]
using the command:

python main.py -u zuck  -i 

the excution stops with the following error

 14:50:07 info:getting content from: 3097159049866530005 [13 of 24] 
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/anyio/streams/tls.py", line 130, in _call_sslobject_method
    result = func(*args)
  File "/usr/local/lib/python3.10/ssl.py", line 916, in read
    v = self._sslobj.read(len)
ssl.SSLWantReadError: The operation did not complete (read) (_ssl.c:2536)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/httpcore/backends/asyncio.py", line 34, in read
    return await self._stream.receive(max_bytes=max_bytes)
  File "/usr/local/lib/python3.10/site-packages/anyio/streams/tls.py", line 195, in receive
    data = await self._call_sslobject_method(self._ssl_object.read, max_bytes)
  File "/usr/local/lib/python3.10/site-packages/anyio/streams/tls.py", line 137, in _call_sslobject_method
    data = await self.transport_stream.receive()
  File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 1265, in receive
    await self._protocol.read_event.wait()
  File "/usr/local/lib/python3.10/asyncio/locks.py", line 213, in wait
    await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/httpcore/_exceptions.py", line 10, in map_exceptions
    yield
  File "/usr/local/lib/python3.10/site-packages/httpcore/backends/asyncio.py", line 32, in read
    with anyio.fail_after(timeout):
  File "/usr/local/lib/python3.10/site-packages/anyio/_core/_tasks.py", line 118, in __exit__
    raise TimeoutError
TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 60, in map_httpcore_exceptions
    yield
  File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 353, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "/usr/local/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 253, in handle_async_request
    raise exc
  File "/usr/local/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 237, in handle_async_request
    response = await connection.handle_async_request(request)
  File "/usr/local/lib/python3.10/site-packages/httpcore/_async/connection.py", line 90, in handle_async_request
    return await self._connection.handle_async_request(request)
  File "/usr/local/lib/python3.10/site-packages/httpcore/_async/http11.py", line 112, in handle_async_request
    raise exc
  File "/usr/local/lib/python3.10/site-packages/httpcore/_async/http11.py", line 91, in handle_async_request
    ) = await self._receive_response_headers(**kwargs)
  File "/usr/local/lib/python3.10/site-packages/httpcore/_async/http11.py", line 155, in _receive_response_headers
    event = await self._receive_event(timeout=timeout)
  File "/usr/local/lib/python3.10/site-packages/httpcore/_async/http11.py", line 191, in _receive_event
    data = await self._network_stream.read(
  File "/usr/local/lib/python3.10/site-packages/httpcore/backends/asyncio.py", line 31, in read
    with map_exceptions(exc_map):
  File "/usr/local/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.10/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc)
httpcore.ReadTimeout

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/New/Picuki/main.py", line 274, in <module>
    asyncio.run(_main(
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/root/New/Picuki/main.py", line 204, in _main
    if (content := await module.get_media_content(media)):
  File "/root/New/Picuki/lib/Picuki.py", line 117, in get_media_content
    page = await self.get("/media/{}".format(
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1757, in get
    return await self.request(
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1533, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1620, in send
    response = await self._send_handling_auth(
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1648, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1685, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1722, in _send_single_request
    response = await transport.handle_async_request(request)
  File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 352, in handle_async_request
    with map_httpcore_exceptions():
  File "/usr/local/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ReadTimeout

the error happens always when the process get the 12th or 13th post with all the username.

**Comment by redfalcoon** [comment]
I've inserted in line 223 of the main.py the following statement time.sleep(5) and with this workaround the error disappears

**Comment by motebaya** [comment]
> I've inserted in line 223 of the main.py the following statement time.sleep(5) and with this workaround the error disappears

exactly, here i add 1 seconds also work as well. and extension file are fixed, because you can see before , the content is videos but saved as images.
https://github.com/motebaya/Picuki/commit/5f2fe52780907690b801e964418fe98bf9217e17
```
 21:39:54 info:getting content from: 3023193647931468548 [24 of 24] 
 21:39:54 debug:send_request_headers.started request=<Request [b'GET']> 
 21:39:54 debug:send_request_headers.complete 
 21:39:54 debug:send_request_body.started request=<Request [b'GET']> 
 21:39:54 debug:send_request_body.complete 
 21:39:54 debug:receive_response_headers.started request=<Request [b'GET']> 
 21:39:54 debug:receive_response_headers.complete return_value=(b'HTTP/1.1', 200, b'OK', [(b'Date', b'Wed, 12 Jul 2023 14:39:54 GMT'), (b'Content-Type', b'text/html; charset=UTF-8'), (b'Transfer-Encoding', b'chunked'), (b'Connection', b'keep-alive'), (b'Vary', b'Accept-Encoding'), (b'CF-Cache-Status', b'DYNAMIC'), (b'Report-To', b'{"endpoints":[{"url":"https:\\/\\/a.nel.cloudflare.com\\/report\\/v3?s=TB69ZSO12q0BjZ1ROJeMqzOHySwkMlQ654mNb8W2cj9Ilvsfwd38n7I8voHLMXgTdebXIWK0gv8mUkgh93p1riYV%2BXlIKhSseNYPcqic%2FRlDzD0SBeTdOdRDOHkStgx2"}],"group":"cf-nel","max_age":604800}'), (b'NEL', b'{"success_fraction":0,"report_to":"cf-nel","max_age":604800}'), (b'Server', b'cloudflare'), (b'CF-RAY', b'7e5a09cb095affac-CGK'), (b'Content-Encoding', b'gzip')]) 
 21:39:54 info:HTTP Request: GET https://www.picuki.com/media/3023193647931468548 "HTTP/1.1 200 OK" 
 21:39:54 debug:receive_response_body.started request=<Request [b'GET']> 
 21:39:54 debug:receive_response_body.complete 
 21:39:54 debug:response_closed.started 
 21:39:54 debug:response_closed.complete 
╭────────── information ───────────╮
│ caption: Gave Beast a haircut 😂 │
│ comments_count: 7,316            │
│ likes_count: 255,517 likes       │
│ name: @zuck                      │
│ time: 5 months ago               │
╰──────────────────────────────────╯
 21:39:54 Warning:there's no videos or thumbnails to download.. ```
