### ISSUE TITLE
Error while downloading media type videos.

### ISSUE THREAD

**Issue by hesaa** [motebaya/Picuki#5]
```
Traceback (most recent call last):
  File "\Picuki\cli.py", line 139, in <module>
    asyncio.run(CLI._main(**vars(args)))
  File "C:\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "\Picuki\cli.py", line 40, in _main
    await Main.downloadMediaContent(
  File "\Picuki\main.py", line 126, in downloadMediaContent
    await Helper._downloadContent(
  File "\Picuki\lib\Helper.py", line 179, in _downloadContent
    f"{output}/{media_type}", Helper.get_valid_filename(
  File "\Picuki\lib\Helper.py", line 116, in get_valid_filename
    if (basename := re.search(r"^https?\:\/\/[^<]+\/q\/(?P<filename>[^\"].*?)\|\|", url)):        
  File "C:\Python310\lib\re.py", line 200, in search
    return _compile(pattern, flags).search(string)
TypeError: expected string or bytes-like object
```

I thinks it's gona solve this problem:

main.py:126
```
                            if('url' in cont):
                                cont = cont['url']
```

**Comment by motebaya** [comment]
Ah yes, thanks. i forgot cause before i've only test it for images only.
the reason is [images type](https://github.com/motebaya/Picuki/blob/2f831248dbcc8b135aa729dd2e2f8f616c16d600/lib/Picuki.py#L208): `list[str]`  and [videos/thumbnails](https://github.com/motebaya/Picuki/blob/2f831248dbcc8b135aa729dd2e2f8f616c16d600/lib/Picuki.py#L184): `list[dict[str, str]]` cause joined in one dict.
